-- Create USERS table
CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(255) NOT NULL,
    phone_number VARCHAR2(50),
    user_type VARCHAR2(50) NOT NULL CHECK (user_type IN ('author', 'admin', 'client')),
    CONSTRAINT users_pk PRIMARY KEY (user_id)
);

-- Create AUTHORS table
CREATE TABLE AUTHORS (
    author_id NUMBER NOT NULL,
    CONSTRAINT authors_pk PRIMARY KEY (author_id),
    CONSTRAINT authors_fk FOREIGN KEY (author_id) REFERENCES USERS (user_id) ON DELETE CASCADE
);

-- Create ADMINS table
CREATE TABLE ADMINS (
    admin_id NUMBER NOT NULL,
    CONSTRAINT admins_pk PRIMARY KEY (admin_id),
    CONSTRAINT admins_fk FOREIGN KEY (admin_id) REFERENCES USERS (user_id) ON DELETE CASCADE
);

-- Create CLIENTS table
CREATE TABLE CLIENTS (
    client_id NUMBER NOT NULL,
    CONSTRAINT clients_pk PRIMARY KEY (client_id),
    CONSTRAINT clients_fk FOREIGN KEY (client_id) REFERENCES USERS (user_id) ON DELETE CASCADE
);

-- Create BOOKS table
CREATE TABLE BOOKS (
    book_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(255) NOT NULL,
    stock NUMBER DEFAULT 0,
    author_id NUMBER NOT NULL,
    CONSTRAINT books_pk PRIMARY KEY (book_id),
    CONSTRAINT books_fk_author FOREIGN KEY (author_id) REFERENCES AUTHORS (author_id) ON DELETE CASCADE
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    client_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    order_date DATE DEFAULT SYSDATE,
    CONSTRAINT orders_pk PRIMARY KEY (order_id),
    CONSTRAINT orders_fk_client FOREIGN KEY (client_id) REFERENCES CLIENTS (client_id) ON DELETE CASCADE,
    CONSTRAINT orders_fk_book FOREIGN KEY (book_id) REFERENCES BOOKS (book_id) ON DELETE CASCADE
);

-- Create FEEDBACK table
CREATE TABLE FEEDBACK (
    feedback_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    client_id NUMBER NOT NULL,
    author_id NUMBER NOT NULL,
    feedback_message VARCHAR2(4000),
    feedback_date DATE DEFAULT SYSDATE,
    CONSTRAINT feedback_pk PRIMARY KEY (feedback_id),
    CONSTRAINT feedback_fk_client FOREIGN KEY (client_id) REFERENCES CLIENTS (client_id) ON DELETE CASCADE,
    CONSTRAINT feedback_fk_author FOREIGN KEY (author_id) REFERENCES AUTHORS (author_id) ON DELETE CASCADE
);